# A tag 'version' foi removida por ser obsoleta
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
      - "8081:8081/udp"
    networks:
      - app-network
    restart: unless-stopped

  bots:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # O comando agora inicia 1000 bots em um único contêiner
    command: ["./client", "-bot", "-count=10", "-prefix=Bot", "server"]
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge