version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080" # Porta TCP
      - "8081:8081/udp" # Porta UDP
    networks:
      - app-network
    # Adicionado para reiniciar o servidor em caso de falha
    restart: unless-stopped


  player1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador1", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador2", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador3", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player4:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador4", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player5:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador5", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player6:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador6", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player7:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador7", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player8:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador8", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player9:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador9", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

  player10:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    # ATUALIZAÇÃO: Adicionada a flag "-bot" para iniciar em modo automatizado
    command: ["./client", "-bot", "Jogador10", "server"]
    networks:
      - app-network
    # stdin_open e tty não são mais necessários para o bot, mas não atrapalham
    stdin_open: true 
    tty: true
    # Adicionado para que o bot não reinicie após terminar a partida
    restart: on-failure

networks:
  app-network:
    driver: bridge
